#!/usr/bin/env bash

# Make sure this script does not kill your laptop.
/usr/bin/renice +19 -p $$ >/dev/null 2>&1
/usr/bin/ionice -c2 -n7 -p $$ >/dev/null 2>&1

# Interval in seconds to check for VMs availability.
DELAY=10


### Validate settings.
if ! [ -f Settings ]; then
    echo "Error: Settings file does not exist yet.
Create one from Settings-example and change to your needs."
    exit -2
fi
source Settings

case "$1" in

create)
    . script/create.sh
    create_infra
    configure_bastion
    ;;

env)
    . script/env.sh
    configure_env
    ;;

start)
    . script/start.sh
    cluster_start
    ;;

stop)
    . script/stop.sh
    cluster_stop
    ;;

destroy)
    . script/destroy.sh
    cluster_destroy
    ;;

*|'')
    . script/ops.sh
    show_help
    ;;

esac
