#!/usr/bin/env bash

# Make sure this script does not kill your system.
/usr/bin/renice +19 -p $$ >/dev/null 2>&1
/usr/bin/ionice -c2 -n7 -p $$ >/dev/null 2>&1

# Interval in seconds to check for VMs availability.
DELAY=10


### Validate settings.
if ! [ -f Settings ]; then
    echo "
    Error: Settings file does not exist.
           Make a copy from 'Settings-example', and 
           edit 'Settings' according to your needs:

           $ cp Settings-example Settings
           
           "
    exit -2
fi
source Settings

case "$1" in

create)

    if ! ([ -f ~/.ansible-vault.password ] && [ -f ~/.rh.yaml ]); then
        echo "
Red Hat Subscription credential files do not exist!

Create the encrypted file '~/.rh.yaml' used by Ansible with:

~~~
$ ansible-vault create ~/.rh.yaml    # A password will be asked to encrypt the file.
~~~

With the YAML content:

~~~
---
rh_username: <RH Username>
rh_password: <RH Password>
~~~

Save the encryption password in the file '~/.ansible-vault.password':

~~~
$ cat ~/.ansible-vault.password
my_encryption_password
~~~

"

        exit 1
    fi

    . script/ops.sh
    . script/create.sh
    . script/configure.sh
    create_infra
    configure_bastion
    show_help_install
    ;;

# For debug only. Not documented option.
ansible-only)
    . script/ops.sh
    . script/configure.sh
    configure_bastion
    show_help_install
    ;;

env)
    . script/env.sh
    configure_env
    ;;

start)
    . script/start.sh
    cluster_start
    ;;

stop)
    . script/stop.sh
    cluster_stop
    ;;

destroy)
    . script/destroy.sh
    cluster_destroy
    ;;

*|'')
    . script/ops.sh
    show_help
    ;;

esac
