---

# ntp server!!!
# https://www.golinuxcloud.com/configure-chrony-ntp-server-client-force-sync/

- name: Configure NTP as Server
  ansible.builtin.template:
    src: files/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: false

- name: Restart and enable chronyd.service
  ansible.builtin.systemd:
    name: chronyd.service
    state: started
    enabled: true

- name: Configure Firewalld
  ansible.posix.firewalld:
    service: ntp
    state: enabled
    permanent: true
    immediate: true
