---
# dhcpd: ips, names and mac addresses.
# /etc/dhcp/dhcpd.conf

- name: Configure /etc/dhcp/dhcpd.conf
  ansible.builtin.template:
    src: files/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0640'
    backup: false

# DOES NOT WORK!
# - name: Make sure there are no leases from old macs
#   ansible.builtin.copy:
#     src: /var/lib/dhcpd/dhcpd.leases~
#     dest: /var/lib/dhcpd/dhcpd.leases
#     owner: dhcpd
#     group: dhcpd
#     mode: '0644'
#     remote_src: true

- name: Reset dhcp leases file
  ansible.builtin.copy:
    dest: /var/lib/dhcpd/dhcpd.leases
    content: ''
    owner: dhcpd
    group: dhcpd
    mode: '0644'
    force: true

- name: Restart and enable dhcpd.service
  ansible.builtin.systemd:
    name: dhcpd.service
    state: restarted
    enabled: true

- name: Configure Firewalld
  ansible.posix.firewalld:
    service: dhcp
    state: enabled
    permanent: true
    immediate: true
