---

# httpd: port 81, ignition and pxe files.

- name: Reconfigure httpd service
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^(Listen)\s+80\s*$'
    replace: '\1 81'

- name: Restart and enable httpd.service
  ansible.builtin.systemd:
    name: httpd.service
    state: started
    enabled: true

- name: Permit traffic in port 81/tcp
  ansible.posix.firewalld:
    port: "81/tcp"
    permanent: true
    immediate: true
    state: enabled
