---
# named: ips and names.
# /etc/named.conf

- name: Configure /etc/named.conf
  ansible.builtin.template:
    src: files/named/named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0740'
    backup: false
    validate: /usr/sbin/named-checkconf %s

- name: Configure dns zone
  ansible.builtin.template:
    src: files/named/zone.db.j2
    dest: /var/named/dynamic/{{ cluster_domain }}.db
    owner: root
    group: named
    mode: '0740'
    backup: false
    validate: /usr/sbin/named-checkzone "{{ cluster_domain }}" %s

- name: Configure dns reverse
  ansible.builtin.template:
    src: files/named/reverse.db.j2
    dest: /var/named/dynamic/{{ network_reverse }}.in-addr.arpa.db
    owner: root
    group: named
    mode: '0740'
    backup: false
    validate: /usr/sbin/named-checkzone "{{ network_reverse }}.in-addr.arpa" %s

- name: Restart and enable named.service
  ansible.builtin.systemd:
    name: named.service
    state: started
    enabled: true

- name: Configure Firewalld
  ansible.posix.firewalld:
    service: dns
    state: enabled
    permanent: true
    immediate: true
