---
# dhcpd: ips, names and mac addresses.
# /etc/dhcp/dhcpd.conf

- name: Configure /etc/dhcp/dhcpd.conf
  ansible.builtin.template:
    src: files/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0640'
    backup: false

- name: Restart and enable dhcpd.service
  ansible.builtin.systemd:
    name: dhcpd.service
    state: started
    enabled: true

- name: Configure Firewalld
  ansible.posix.firewalld:
    service: dhcp
    state: enabled
    permanent: true
    immediate: true
