---

#
# Generate a valid openshift-install
#

# CA only for registry
- name: Collect data for the install-config.yaml with mirror registry
  when: registry
  block:

    - name: Get the CA cert into a variable
      ansible.builtin.command:
        cmd: awk '{$1="  "$1}1' /root/CA/CA_cert.pem
      register: ca_cert

    - name: Show CA content
      debug:
          var: ca_cert


# Pull secret.
#
# With registry == /root/pull-secret-mirror.json
# No registry   == /root/pull-secret.txt
#
# "when" clause fails because if a task fails or is skipped, 
# the variable still is registered with a failure or skipped status"

- name: Set pull-secret file - registry
  ansible.builtin.set_fact:
    pullfile: /root/pull-secret-mirror.json
  when: registry

- name: Set pull-secret file - NO registry
  ansible.builtin.set_fact:
    pullfile: /root/pull-secret.txt
  when: not registry

- name: Get the pull secret into a variable
  ansible.builtin.shell:
    cmd: cat {{ pullfile }} | jq -c .
  register: pull_secret

- name: Show pull-secret
  debug:
    var: pull_secret


# SSH key is collected for all.

- name: Get the SSH public key in a a variable
  ansible.builtin.command:
    cmd: cat /root/.ssh/id_rsa.pub
  register: ssh_public_key

- name: Show SSH public key
  debug:
    var: ssh_public_key


# Assemble!

- name: Assemble the install-config.yaml
  ansible.builtin.template:
    src: files/ocp-install/install-config.yaml.j2
    dest: /root/install-config.yaml
    owner: root
    group: root
    mode: '0644'
    backup: false

- name: Copy agent-config.yaml to bastion
  ansible.builtin.template:
    src: files/ocp-install/agent-config.yaml.j2
    dest: /root/agent-config.yaml
    owner: root
    group: root
    mode: '0644'
    backup: false
  when: installation_method == 'ABI'


- name: Test the existence of an existing install-dir. REMOVE TO RECREATE!!!
  ansible.builtin.stat:
    path: /root/install-dir
  register: check_dir

- name: Prepare install-dir and config files
  when: not check_dir.stat.exists
  block:

    - name: Create install-dir
      ansible.builtin.file:
        path: /root/install-dir
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy install-config.yaml to install-dir
      ansible.builtin.copy:
        src: /root/install-config.yaml
        dest: /root/install-dir/install-config.yaml
        owner: root
        group: root
        mode: '0640'
        remote_src: true

    - name: Copy agent-config.yaml to install-dir
      ansible.builtin.copy:
        src: /root/agent-config.yaml
        dest: /root/install-dir/agent-config.yaml
        owner: root
        group: root
        mode: '0640'
        remote_src: true
      when: installation_method == 'ABI'


- name: Prepare install-dir and config files
  when: not check_dir.stat.exists and installation_method == 'UPI'
  block:

    - name: Create ignition files
      ansible.builtin.shell:
        cmd: PATH=$PATH:/root/bin openshift-install --dir install-dir create ignition-configs
      args:
        chdir: /root/

    - name: Copy ignition files to http server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html
        owner: apache
        group: apache
        mode: '0664'
        remote_src: true
      with_items:
        - /root/{{ cluster_name }}/bootstrap.ign
        - /root/{{ cluster_name }}/master.ign
        - /root/{{ cluster_name }}/worker.ign
