---

- name: Copy SSH key to bastion
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/.ssh/
    owner: root
    group: root
    mode: '0400'
  with_items:
    - ../ssh/id_rsa
    - ../ssh/id_rsa.pub

- name: Copy pull-secret to bastion
  ansible.builtin.copy:
    src: "{{ pull_secret }}"
    dest: /root/
    owner: root
    group: root
    mode: '0640'
