# Untested

# Generated by Anaconda 34.24.9
# Generated by pykickstart v3.32
#version=DEVEL
# Use graphical install
graphical

# Keyboard layouts
keyboard --xlayouts='gb'
# System language
lang en_GB.UTF-8

# Network information
network  --bootproto=static --device=enp1s0 --gateway=192.168.100.1 --ip=192.168.100.9 --nameserver=192.168.100.1 --netmask=255.255.255.0 --ipv6=auto --activate
network  --hostname=lb.c499.ocp.com

# Use CDROM installation media
cdrom

%packages
@^server-product-environment
@guest-agents

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.3.3
ignoredisk --only-use=vda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone Europe/London --utc

#Root password
rootpw --lock
user --groups=wheel --name=admin --password=$6$5Fz4zS3KlePO4ySR$cyKG5YKedMYtueR3t7n2cR6XCqgyZB8GhIQu0n0TIoSOUJPwdMOfY8FnyFHFinuk.h8vvyKWEo4pmugyrcOC2/ --iscrypted --gecos="admin"
