---

- name: Bastion configuration tasks
  hosts: bastion

  vars_files:
    - vars/common.yaml
    - ~/.rh.yaml

  tasks:

    ### bastion host tasks

    - name: Configure bastion host
      ansible.builtin.import_tasks: tasks/bastion-host.yaml
      tags:
        - host

    - name: Configure bastion named service
      ansible.builtin.import_tasks: tasks/bastion-named.yaml
      tags:
        - named

    - name: Configure bastion dhcpd service
      ansible.builtin.import_tasks: tasks/bastion-dhcpd.yaml
      tags:
        - dhcpd

    - name: Configure bastion tftp/pxe service
      ansible.builtin.import_tasks: tasks/bastion-tftp.yaml
      tags:
        - tftp

    - name: Configure bastion web server
      ansible.builtin.import_tasks: tasks/bastion-web.yaml
      tags:
        - web

    - name: Configure bastion haproxy service
      ansible.builtin.import_tasks: tasks/bastion-haproxy.yaml
      tags:
        - haproxy

    - name: Configure bastion ntp service
      ansible.builtin.import_tasks: tasks/bastion-ntp.yaml
      tags:
        - ntp

    - name: Configure NFS Server for OpenShift Internal Registry
      ansible.builtin.import_tasks: tasks/bastion-registry-nfs.yaml
      when: registry_nfs
      tags:
        - registry-nfs

    ### Install tasks

    - name: Installation preparation tasks
      ansible.builtin.import_tasks: tasks/install-prepare.yaml
      tags:
        - inst-prepare

    - name: Install PXE RHCOS boot files
      ansible.builtin.import_tasks: tasks/install-pxe-rhcos-files.yaml
      tags:
        - inst-pxe-rhcos

    - name: Install Proxy server
      ansible.builtin.import_tasks: tasks/install-proxy.yaml
      when: proxy
      tags:
        - inst-proxy

    - name: Install mirror registry
      when: registry
      block:
        - name: Create CA cert
          ansible.builtin.import_tasks: tasks/install-create-CA.yaml
          tags:
            - inst-CA

        - name: Create registry mirror
          ansible.builtin.import_tasks: tasks/install-mirror.yaml
          tags:
            - inst-mirror

    - name: Assemble install-config.yaml
      ansible.builtin.import_tasks: tasks/install-config.yaml
      tags:
        - inst-config

    - name: Messages !!!
      ansible.builtin.debug:
        msg:
          - "Some decisions were made to speed up the preparation time:"
          - "  - The bastion was not updated. Update with 'dnf update'"
          - "  - The mirror registry sync was delayed until the very end, not to delay any other operations. The sync will start now if available."


    - name: Execute the oc-mirror command
      when: registry
      block:
        - name: GO TAKE A COFFEE!!!
          ansible.builtin.shell: |
            PATH=$PATH:/root/bin oc-mirror --v2 \
              -c imageset-config.yaml \
              --workspace file:///root/oc-mirror/ \
              docker://bastion.c41627.ocp.local:5000
          args:
            executable: /bin/bash
          register: my_output             # <- Registers the command output.
          changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

        - name: Mirror sync output
          ansible.builtin.debug:
            var: my_output
