---

- name: Bastion configuration tasks
  hosts: bastion

  vars_files:
    - vars/common.yaml

  tasks:

    ### bastion host tasks

    - name: Configure bastion host
      ansible.builtin.import_tasks: tasks/bastion-host.yaml
      tags:
        - host

    - name: Configure bastion named service
      ansible.builtin.import_tasks: tasks/bastion-named.yaml
      tags:
        - named

    - name: Configure bastion dhcpd service
      ansible.builtin.import_tasks: tasks/bastion-dhcpd.yaml
      tags:
        - dhcpd

    - name: Configure bastion tftp/pxe service
      ansible.builtin.import_tasks: tasks/bastion-tftp.yaml
      tags:
        - tftp

    - name: Configure bastion web server
      ansible.builtin.import_tasks: tasks/bastion-web.yaml
      tags:
        - web

    - name: Configure bastion haproxy service
      ansible.builtin.import_tasks: tasks/bastion-haproxy.yaml
      tags:
        - haproxy

    - name: Configure bastion ntp service
      ansible.builtin.import_tasks: tasks/bastion-ntp.yaml
      tags:
        - ntp

    - name: Configure NFS Server for OpenShift Internal Registry
      ansible.builtin.import_tasks: tasks/bastion-registry-nfs.yaml
      when: registry_nfs
      tags:
        - registry-nfs

    ### Install tasks

    - name: Installation preparation tasks
      ansible.builtin.import_tasks: tasks/install-prepare.yaml
      tags:
        - inst-prepare

    - name: Install PXE RHCOS boot files
      ansible.builtin.import_tasks: tasks/install-pxe-rhcos-files.yaml
      tags:
        - inst-pxe-rhcos

    - name: Install OCP client tools
      ansible.builtin.import_tasks: tasks/install-client-tools.yaml
      tags:
        - inst-cli-tools

    - name: Create CA cert
      ansible.builtin.import_tasks: tasks/install-create-CA.yaml
      tags:
        - inst-CA

    - name: Create registry mirror
      ansible.builtin.import_tasks: tasks/install-mirror.yaml
      tags:
        - inst-mirror

    - name: Assemble install-config.yaml
      ansible.builtin.import_tasks: tasks/install-config.yaml
      tags:
        - inst-config
